"""unique connection per sender and rfq

Revision ID: 103ffa3610a4
Revises: e1f2adb24eb9
Create Date: 2026-09-19 16:59:23.664485
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '103ffa3610a4'
down_revision: Union[str, None] = 'e1f2adb24eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_connections_sender_rfq', 'connections', ['sender_id', 'rfq_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_connections_sender_rfq', 'connections', type_='unique')
    # ### end Alembic commands ###
