"""Add minimum order to RFQ

Revision ID: 7aa3c4b87a6c
Revises: 5c0d68b11738
Create Date: 2026-09-19 14:17:44.506287
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7aa3c4b87a6c'
down_revision: Union[str, None] = '5c0d68b11738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('min_order_value', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('rfqs', sa.Column('min_order_unit', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'min_order_unit')
    op.drop_column('rfqs', 'min_order_value')
    # ### end Alembic commands ###
