"""initial schema

Revision ID: ac695676cd4f
Revises: 
Create Date: 2026-09-19 10:29:25.664298
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ac695676cd4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'seller', 'both', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending_verification', 'active', 'suspended', 'deleted', name='user_status'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email', 'users', ['email'], unique=True)
    op.create_table('rfqs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'seller', name='rfq_role'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'expired', 'closed', name='rfq_status'), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity_unit', sa.String(length=32), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('price_per_unit', sa.String(length=32), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('location_state', sa.String(length=120), nullable=True),
    sa.Column('location_country', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_raw', sa.String(length=300), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_raw', sa.String(length=160), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('search_tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'indexed', 'failed', 'stale', name='embedding_status'), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfqs_category_status', 'rfqs', ['category', 'status'], unique=False)
    op.create_index('ix_rfqs_embedding_status', 'rfqs', ['embedding_status'], unique=False)
    op.create_index('ix_rfqs_expires_at', 'rfqs', ['expires_at'], unique=False)
    op.create_index('ix_rfqs_product_details', 'rfqs', ['product_details'], unique=False, postgresql_using='gin')
    op.create_index('ix_rfqs_role_status', 'rfqs', ['role', 'status'], unique=False)
    op.create_index('ix_rfqs_search_tags', 'rfqs', ['search_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_rfqs_user_created', 'rfqs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_city'), 'user_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('onboarding', 'direct_search', name='conversation_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('rfq_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('match_searches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('requester_role', sa.Enum('buyer', 'seller', name='match_requester_role'), nullable=False),
    sa.Column('target_role', sa.Enum('buyer', 'seller', name='match_target_role'), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('shown_rfq_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('last_cursor', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_searches_query_hash'), 'match_searches', ['query_hash'], unique=False)
    op.create_index('ix_match_searches_user_created', 'match_searches', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('match_results',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['match_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'rfq_id', name='uq_match_results_search_rfq')
    )
    op.create_index('ix_match_results_search_rank', 'match_results', ['search_id', 'rank'], unique=False)
    op.create_table('message_events',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'sequence', name='uq_message_events_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_events')
    op.drop_index('ix_match_results_search_rank', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_match_searches_user_created', table_name='match_searches')
    op.drop_index(op.f('ix_match_searches_query_hash'), table_name='match_searches')
    op.drop_table('match_searches')
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_city'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_rfqs_user_created', table_name='rfqs')
    op.drop_index('ix_rfqs_search_tags', table_name='rfqs', postgresql_using='gin')
    op.drop_index('ix_rfqs_role_status', table_name='rfqs')
    op.drop_index('ix_rfqs_product_details', table_name='rfqs', postgresql_using='gin')
    op.drop_index('ix_rfqs_expires_at', table_name='rfqs')
    op.drop_index('ix_rfqs_embedding_status', table_name='rfqs')
    op.drop_index('ix_rfqs_category_status', table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index('uq_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Alembic's drop_table leaves behind the PostgreSQL enum types that
    # create_table implicitly created. Without this, a downgrade followed by an
    # upgrade fails with "type user_role already exists".
    for enum_name in (
        'message_role',
        'match_target_role',
        'match_requester_role',
        'conversation_type',
        'embedding_status',
        'rfq_status',
        'rfq_role',
        'user_status',
        'user_role',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
