"""add quotations table and deal room enums

Revision ID: bf84077ffed1
Revises: 103ffa3610a4
Create Date: 2026-09-19 23:37:23.861956
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf84077ffed1'
down_revision: Union[str, None] = '103ffa3610a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('quote_number', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'countered', 'expired', name='quotation_status'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_unit', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('incoterms', sa.Enum('EXW', 'FOB', 'CIF', 'CFR', 'DDP', 'CIP', name='incoterm'), nullable=True),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('purchase_order_reference', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotations_connection_created', 'quotations', ['connection_id', 'created_at'], unique=False)
    op.create_index('ix_quotations_receiver_id', 'quotations', ['receiver_id'], unique=False)
    op.create_index('ix_quotations_sender_id', 'quotations', ['sender_id'], unique=False)
    op.create_index('ix_quotations_status', 'quotations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotations_status', table_name='quotations')
    op.drop_index('ix_quotations_sender_id', table_name='quotations')
    op.drop_index('ix_quotations_receiver_id', table_name='quotations')
    op.drop_index('ix_quotations_connection_created', table_name='quotations')
    op.drop_table('quotations')
    sa.Enum(name='quotation_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incoterm').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

