"""add reviews certificates moderation and kyc fields

Revision ID: de7609ddea6e
Revises: bf84077ffed1
Create Date: 2026-09-20 08:23:35.010851
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de7609ddea6e'
down_revision: Union[str, None] = 'bf84077ffed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Expand quotation_status enum
    op.execute("ALTER TYPE quotation_status ADD VALUE IF NOT EXISTS 'delivered'")
    op.execute("ALTER TYPE quotation_status ADD VALUE IF NOT EXISTS 'completed'")

    # Create kyc_status enum type before adding column
    kyc_status_enum = sa.Enum('unverified', 'pending', 'verified', 'flagged', name='kyc_status')
    kyc_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('issuing_body', sa.String(length=160), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='certification_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certificates_user_id', 'certificates', ['user_id'], unique=False)
    op.create_index('ix_certificates_verification_status', 'certificates', ['verification_status'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('flagged_terms', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_logs_category', 'moderation_logs', ['category'], unique=False)
    op.create_index('ix_moderation_logs_user_id', 'moderation_logs', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('delivery_rating', sa.Integer(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id', 'reviewer_id', name='uq_review_quotation_reviewer')
    )
    op.create_index('ix_reviews_quotation_id', 'reviews', ['quotation_id'], unique=False)
    op.create_index('ix_reviews_reviewee_id', 'reviews', ['reviewee_id'], unique=False)
    op.create_index('ix_reviews_reviewer_id', 'reviews', ['reviewer_id'], unique=False)
    op.add_column('user_profiles', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('legal_business_name', sa.String(length=200), nullable=True))
    op.add_column('user_profiles', sa.Column('business_type', sa.String(length=60), nullable=True))
    op.add_column('user_profiles', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('signatory_name', sa.String(length=120), nullable=True))
    op.add_column('user_profiles', sa.Column('kyc_status', sa.Enum('unverified', 'pending', 'verified', 'flagged', name='kyc_status', create_type=False), server_default='unverified', nullable=False))
    op.add_column('user_profiles', sa.Column('trust_score', sa.Integer(), server_default='20', nullable=False))
    op.create_index(op.f('ix_user_profiles_gst_number'), 'user_profiles', ['gst_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_gst_number'), table_name='user_profiles')
    op.drop_column('user_profiles', 'trust_score')
    op.drop_column('user_profiles', 'kyc_status')
    op.drop_column('user_profiles', 'signatory_name')
    op.drop_column('user_profiles', 'pan_number')
    op.drop_column('user_profiles', 'website')
    op.drop_column('user_profiles', 'year_established')
    op.drop_column('user_profiles', 'registration_number')
    op.drop_column('user_profiles', 'business_type')
    op.drop_column('user_profiles', 'legal_business_name')
    op.drop_column('user_profiles', 'gst_number')
    op.drop_index('ix_reviews_reviewer_id', table_name='reviews')
    op.drop_index('ix_reviews_reviewee_id', table_name='reviews')
    op.drop_index('ix_reviews_quotation_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_moderation_logs_user_id', table_name='moderation_logs')
    op.drop_index('ix_moderation_logs_category', table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index('ix_certificates_verification_status', table_name='certificates')
    op.drop_index('ix_certificates_user_id', table_name='certificates')
    op.drop_table('certificates')

    op.execute("DROP TYPE IF EXISTS certification_status")
    op.execute("DROP TYPE IF EXISTS kyc_status")
    # ### end Alembic commands ###
