"""Add connections and connection_messages

Revision ID: e1f2adb24eb9
Revises: 7aa3c4b87a6c
Create Date: 2026-09-19 15:01:03.171045
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1f2adb24eb9'
down_revision: Union[str, None] = '7aa3c4b87a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='connection_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connections_receiver_id', 'connections', ['receiver_id'], unique=False)
    op.create_index('ix_connections_rfq_id', 'connections', ['rfq_id'], unique=False)
    op.create_index('ix_connections_sender_id', 'connections', ['sender_id'], unique=False)
    op.create_table('connection_messages',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connection_messages_connection_created', 'connection_messages', ['connection_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_connection_messages_connection_created', table_name='connection_messages')
    op.drop_table('connection_messages')
    op.drop_index('ix_connections_sender_id', table_name='connections')
    op.drop_index('ix_connections_rfq_id', table_name='connections')
    op.drop_index('ix_connections_receiver_id', table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
